/* =====================================================================
   SOLO LEVELING — VOCABULARY DATA
   150 words a working professional actually needs. 5 per day, 30 days.
   Edit freely — nothing here affects saved progress.
   ===================================================================== */

const VOCAB = [
  /* ---------- MANAGEMENT & LEADERSHIP ---------- */
  {w:'strategy',        cat:'Management', ar:'استراتيجية',
   def:'A plan of action designed to achieve a long-term goal.',
   ex:'Our strategy for Q4 is to shift budget into TikTok.'},
  {w:'implement',       cat:'Management', ar:'يُنفّذ',
   def:'To put a plan or decision into effect.',
   ex:'We implemented the new tracking setup last week.'},
  {w:'delegate',        cat:'Management', ar:'يُفوّض',
   def:'To give a task or responsibility to someone else.',
   ex:'A good manager delegates reporting, not just the boring parts.'},
  {w:'collaborate',     cat:'Management', ar:'يتعاون',
   def:'To work jointly with others on a project.',
   ex:'The design team collaborates with media buyers on every campaign.'},
  {w:'initiative',      cat:'Management', ar:'مبادرة',
   def:'A new effort or plan intended to achieve something.',
   ex:'The automation initiative cut our reporting time in half.'},
  {w:'milestone',       cat:'Management', ar:'مرحلة إنجاز',
   def:'A significant checkpoint in a project.',
   ex:'Hitting 10,000 leads was a real milestone for the account.'},
  {w:'roadmap',         cat:'Management', ar:'خارطة طريق',
   def:'A planned timeline of major work.',
   ex:'The product roadmap shows three launches this year.'},
  {w:'scope',           cat:'Management', ar:'نطاق العمل',
   def:'The boundaries of what a project includes.',
   ex:'That request is out of scope — it is a separate project.'},
  {w:'objective',       cat:'Management', ar:'هدف',
   def:'A specific, measurable target.',
   ex:'Our objective is a CPL under 50.'},
  {w:'prioritise',      cat:'Management', ar:'يرتّب حسب الأولوية',
   def:'To arrange tasks in order of importance.',
   ex:'Prioritise the campaigns that are still spending.'},
  {w:'headcount',       cat:'Management', ar:'عدد الموظفين',
   def:'The number of employees in an organisation.',
   ex:'We are holding headcount flat until revenue grows.'},
  {w:'onboarding',      cat:'Management', ar:'تهيئة الموظف الجديد',
   def:'The process of integrating a new employee.',
   ex:'Onboarding takes two weeks and includes account access.'},
  {w:'performance review', cat:'Management', ar:'تقييم الأداء',
   def:'A formal evaluation of an employee\u2019s work.',
   ex:'My performance review is in December.'},
  {w:'line manager',    cat:'Management', ar:'المدير المباشر',
   def:'The person directly responsible for supervising you.',
   ex:'Ask your line manager before changing the budget.'},

  /* ---------- FINANCE & NUMBERS ---------- */
  {w:'budget',          cat:'Finance', ar:'ميزانية',
   def:'A financial plan of expected income and expenses.',
   ex:'The monthly budget is TL 171,000 across 27 campaigns.'},
  {w:'revenue',         cat:'Finance', ar:'إيرادات',
   def:'Income generated from business activity.',
   ex:'Revenue grew 18% quarter on quarter.'},
  {w:'profit',          cat:'Finance', ar:'ربح',
   def:'What is left after costs are deducted from revenue.',
   ex:'We hit revenue targets but the profit margin is thin.'},
  {w:'margin',          cat:'Finance', ar:'هامش الربح',
   def:'The difference between revenue and costs.',
   ex:'Agencies live and die on their margin.'},
  {w:'gross margin',    cat:'Finance', ar:'الهامش الإجمالي',
   def:'Revenue minus the direct cost of delivering.',
   ex:'Our gross margin on media buying is around 20%.'},
  {w:'invoice',         cat:'Finance', ar:'فاتورة',
   def:'A document requesting payment for goods or services.',
   ex:'Send the invoice on the first of the month.'},
  {w:'payment terms',   cat:'Finance', ar:'شروط الدفع',
   def:'The agreed schedule and method of payment.',
   ex:'Our payment terms are net 30.'},
  {w:'cash flow',       cat:'Finance', ar:'التدفق النقدي',
   def:'The movement of money in and out of a business.',
   ex:'Profitable companies still die from bad cash flow.'},
  {w:'overhead',        cat:'Finance', ar:'المصاريف الثابتة',
   def:'Ongoing operating costs not tied to a specific job.',
   ex:'Keep overhead low in your first year as an agency.'},
  {w:'forecast',        cat:'Finance', ar:'توقّع',
   def:'A prediction of future performance.',
   ex:'The forecast says we need 40 more leads a day.'},
  {w:'audit',           cat:'Finance', ar:'تدقيق',
   def:'A thorough examination of financial records.',
   ex:'The client ran an audit of our ad spend.'},
  {w:'leverage',        cat:'Finance', ar:'استغلال لصالحك',
   def:'To use something to maximum advantage.',
   ex:'Leverage your Meta experience when you negotiate salary.'},
  {w:'liability',       cat:'Finance', ar:'التزام مالي',
   def:'A debt or financial obligation.',
   ex:'Unpaid invoices are a liability, not an asset.'},
  {w:'ROI',             cat:'Finance', ar:'العائد على الاستثمار',
   def:'Return on investment \u2014 how efficient a spend was.',
   ex:'The client wants to know the ROI on every channel.'},
  {w:'break even',      cat:'Finance', ar:'نقطة التعادل',
   def:'The point where costs equal income.',
   ex:'We break even at around 2,000 leads a month.'},

  /* ---------- MARKETING & ADVERTISING ---------- */
  {w:'campaign',        cat:'Marketing', ar:'حملة',
   def:'An organised series of advertising activities.',
   ex:'The Ramadan campaign delivered 1,544 leads.'},
  {w:'audience',        cat:'Marketing', ar:'الجمهور المستهدف',
   def:'The group of people a campaign is aimed at.',
   ex:'The audience was too broad, so the CPL stayed high.'},
  {w:'reach',           cat:'Marketing', ar:'الوصول',
   def:'The number of unique people who saw content.',
   ex:'Reach was high but conversion was low.'},
  {w:'engagement',      cat:'Marketing', ar:'التفاعل',
   def:'Likes, comments, shares and saves on a post.',
   ex:'Engagement doubled after we changed the hook.'},
  {w:'conversion',      cat:'Marketing', ar:'التحويل',
   def:'When someone completes the desired action.',
   ex:'The landing page is killing our conversion rate.'},
  {w:'conversion rate', cat:'Marketing', ar:'معدل التحويل',
   def:'The percentage of people who take the desired action.',
   ex:'A 4% conversion rate is solid for lead gen.'},
  {w:'funnel',          cat:'Marketing', ar:'قمع التسويق',
   def:'The stages a customer passes through before buying.',
   ex:'Most of our leads drop out at the top of the funnel.'},
  {w:'retargeting',     cat:'Marketing', ar:'إعادة الاستهداف',
   def:'Advertising again to people who already interacted.',
   ex:'Retargeting is the cheapest lead source we have.'},
  {w:'creative',        cat:'Marketing', ar:'المادة الإعلانية',
   def:'The actual ad \u2014 image, video, or copy.',
   ex:'The creative is what decides the CPL, not the targeting.'},
  {w:'hook',            cat:'Marketing', ar:'الجملة الافتتاحية',
   def:'The opening line that stops someone scrolling.',
   ex:'A weak hook costs more than a weak offer.'},
  {w:'placement',       cat:'Marketing', ar:'مكان الظهور',
   def:'Where an ad appears \u2014 feed, story, reels.',
   ex:'Story placements outperform feed for this audience.'},
  {w:'impression',      cat:'Marketing', ar:'مرة ظهور',
   def:'One instance of an ad being displayed.',
   ex:'We bought 2 million impressions this month.'},
  {w:'frequency',       cat:'Marketing', ar:'تكرار الظهور',
   def:'How often the same person sees your ad.',
   ex:'Frequency above 4 starts to annoy people.'},
  {w:'brand awareness', cat:'Marketing', ar:'الوعي بالعلامة التجارية',
   def:'How familiar people are with a brand.',
   ex:'This campaign is for brand awareness, not leads.'},
  {w:'positioning',     cat:'Marketing', ar:'التموضع',
   def:'How a product is presented relative to competitors.',
   ex:'Their positioning is premium; ours is affordable.'},
  {w:'copy',            cat:'Marketing', ar:'النص الإعلاني',
   def:'The written text in an advertisement.',
   ex:'Short copy usually beats long copy on mobile.'},
  {w:'call to action',  cat:'Marketing', ar:'دعوة لاتخاذ إجراء',
   def:'The instruction telling the audience what to do.',
   ex:'Every ad needs a clear call to action.'},
  {w:'landing page',    cat:'Marketing', ar:'صفحة الهبوط',
   def:'The page a user arrives at after clicking an ad.',
   ex:'Fix the landing page before you raise the budget.'},
  {w:'lead quality',    cat:'Marketing', ar:'جودة العملاء المحتملين',
   def:'How likely a lead is to become a real customer.',
   ex:'Cheap leads are useless if the lead quality is bad.'},
  {w:'attribution',     cat:'Marketing', ar:'إسناد النتائج',
   def:'Crediting conversions to the right channel.',
   ex:'Attribution is messy once you run three platforms.'},
  {w:'organic',         cat:'Marketing', ar:'غير مدفوع',
   def:'Content that earns reach without paid spend.',
   ex:'Organic reach is down, so we pay for distribution.'},
  {w:'media buying',    cat:'Marketing', ar:'شراء المساحات الإعلانية',
   def:'The job of planning and purchasing ad space.',
   ex:'Media buying is 20% setup and 80% reading the data.'},

  /* ---------- DATA & ANALYTICS ---------- */
  {w:'metric',          cat:'Data', ar:'مقياس',
   def:'A number used to measure performance.',
   ex:'CPL is the metric that matters most here.'},
  {w:'benchmark',       cat:'Data', ar:'معيار مرجعي',
   def:'A standard to compare performance against.',
   ex:'The industry benchmark for this sector is TL 60.'},
  {w:'baseline',        cat:'Data', ar:'خط الأساس',
   def:'The starting measurement before changes.',
   ex:'Our baseline CPL was 130 before the rebuild.'},
  {w:'trend',           cat:'Data', ar:'اتجاه',
   def:'A general direction of change over time.',
   ex:'The trend is down three weeks in a row.'},
  {w:'variance',        cat:'Data', ar:'تباين',
   def:'The amount something differs from the expected value.',
   ex:'High variance means the result is not reliable yet.'},
  {w:'correlation',     cat:'Data', ar:'ارتباط',
   def:'A relationship between two sets of data.',
   ex:'There is a correlation between video length and drop-off.'},
  {w:'outlier',         cat:'Data', ar:'قيمة شاذة',
   def:'A data point far outside the normal range.',
   ex:'That one campaign is an outlier \u2014 ignore it.'},
  {w:'sample size',     cat:'Data', ar:'حجم العينة',
   def:'How many data points you are working with.',
   ex:'The sample size is too small to decide anything.'},
  {w:'segment',         cat:'Data', ar:'شريحة',
   def:'A subgroup of a larger audience.',
   ex:'Split the audience into three segments and test each.'},
  {w:'optimise',        cat:'Data', ar:'يُحسّن',
   def:'To improve performance through changes.',
   ex:'We optimise weekly, not daily.'},
  {w:'scale',           cat:'Data', ar:'يوسّع',
   def:'To increase spend or reach on what is working.',
   ex:'Scale the winner and pause everything else.'},
  {w:'allocation',      cat:'Data', ar:'توزيع الميزانية',
   def:'How budget is divided between options.',
   ex:'Budget allocation should follow performance.'},
  {w:'scalable',        cat:'Data', ar:'قابل للتوسع',
   def:'Able to grow without breaking.',
   ex:'Manual reporting is not scalable past five clients.'},
  {w:'granularity',     cat:'Data', ar:'مستوى التفصيل',
   def:'How detailed the data is.',
   ex:'I need more granularity \u2014 break it down by ad set.'},
  {w:'dashboard',       cat:'Data', ar:'لوحة متابعة',
   def:'A screen showing key metrics at a glance.',
   ex:'Build one dashboard instead of five spreadsheets.'},

  /* ---------- MEETINGS & COMMUNICATION ---------- */
  {w:'agenda',          cat:'Meetings', ar:'جدول الأعمال',
   def:'A list of items to be discussed in a meeting.',
   ex:'Send the agenda the day before, always.'},
  {w:'briefing',        cat:'Meetings', ar:'إحاطة',
   def:'A short meeting to give information or instructions.',
   ex:'The client briefing is at 10am.'},
  {w:'minutes',         cat:'Meetings', ar:'محضر الاجتماع',
   def:'The written record of a meeting\u2019s decisions.',
   ex:'Who is taking the minutes today?'},
  {w:'kickoff',         cat:'Meetings', ar:'اجتماع البداية',
   def:'The first meeting of a project.',
   ex:'The kickoff set expectations for the whole project.'},
  {w:'follow up',       cat:'Meetings', ar:'متابعة',
   def:'To check on something after an initial contact.',
   ex:'I will follow up with them on Thursday.'},
  {w:'next steps',      cat:'Meetings', ar:'الخطوات التالية',
   def:'The agreed actions after the current stage.',
   ex:'Let us close with clear next steps and owners.'},
  {w:'stakeholder',     cat:'Meetings', ar:'صاحب مصلحة',
   def:'Anyone affected by or involved in a project.',
   ex:'Get the stakeholder sign-off before launch.'},
  {w:'alignment',       cat:'Meetings', ar:'توافق',
   def:'Agreement on goals and approach.',
   ex:'We need alignment between sales and marketing.'},
  {w:'blocker',         cat:'Meetings', ar:'عقبة',
   def:'Something preventing progress.',
   ex:'The blocker is that we still do not have ad access.'},
  {w:'bandwidth',       cat:'Meetings', ar:'الطاقة والوقت المتاح',
   def:'The capacity to take on more work.',
   ex:'I do not have the bandwidth for another account.'},
  {w:'loop in',         cat:'Meetings', ar:'يُضيف في النقاش',
   def:'To include someone in a conversation.',
   ex:'Loop in the designer before you promise a deadline.'},
  {w:'touch base',      cat:'Meetings', ar:'تواصل سريع',
   def:'A short informal check-in.',
   ex:'Let us touch base on Monday morning.'},
  {w:'circle back',     cat:'Meetings', ar:'العودة للموضوع لاحقاً',
   def:'To return to a topic later.',
   ex:'We can circle back to pricing after the audit.'},
  {w:'takeaway',        cat:'Meetings', ar:'الخلاصة',
   def:'The main point worth remembering.',
   ex:'The key takeaway is that creative drives cost.'},
  {w:'action item',     cat:'Meetings', ar:'مهمة تنفيذية',
   def:'A specific task assigned in a meeting.',
   ex:'Every action item needs a name and a date.'},

  /* ---------- NEGOTIATION & PRESENTATION ---------- */
  {w:'negotiate',       cat:'Negotiation', ar:'يتفاوض',
   def:'To discuss terms to reach an agreement.',
   ex:'Always negotiate the salary, never the first offer.'},
  {w:'proposal',        cat:'Negotiation', ar:'عرض مقدم',
   def:'A suggested plan offered for approval.',
   ex:'The proposal includes three pricing tiers.'},
  {w:'quote',           cat:'Negotiation', ar:'عرض سعر',
   def:'A stated price for specific work.',
   ex:'Send me a quote for the full rebrand.'},
  {w:'estimate',        cat:'Negotiation', ar:'تقدير',
   def:'An approximate calculation of cost or time.',
   ex:'That estimate is rough \u2014 the scope is unclear.'},
  {w:'retainer',        cat:'Negotiation', ar:'اشتراك شهري',
   def:'A regular fee paid for ongoing services.',
   ex:'A retainer beats project work for cash flow.'},
  {w:'concession',      cat:'Negotiation', ar:'تنازل',
   def:'Something you give up to reach agreement.',
   ex:'Every concession should get something back.'},
  {w:'counteroffer',    cat:'Negotiation', ar:'عرض مقابل',
   def:'A reply to an offer with different terms.',
   ex:'My counteroffer was 15% above their number.'},
  {w:'walk away',       cat:'Negotiation', ar:'الانسحاب من التفاوض',
   def:'To leave a deal that does not meet your terms.',
   ex:'You must be willing to walk away.'},
  {w:'value proposition', cat:'Negotiation', ar:'القيمة المقدمة',
   def:'The reason a customer should choose you.',
   ex:'Our value proposition is speed and tracking rigour.'},
  {w:'pitch',           cat:'Negotiation', ar:'عرض تقديمي للبيع',
   def:'A presentation to sell an idea or service.',
   ex:'The pitch went well \u2014 they asked about onboarding.'},
  {w:'differentiate',   cat:'Negotiation', ar:'يتميّز عن المنافسين',
   def:'To make something clearly different from competitors.',
   ex:'Specialise to differentiate, not to be cheaper.'},
  {w:'upsell',          cat:'Negotiation', ar:'بيع إضافي',
   def:'Selling a more expensive option to an existing client.',
   ex:'Automation is the easiest upsell you can offer.'},
  {w:'testimonial',     cat:'Negotiation', ar:'شهادة عميل',
   def:'A client statement recommending your work.',
   ex:'One good testimonial beats ten claims.'},
  {w:'case study',      cat:'Negotiation', ar:'دراسة حالة',
   def:'A detailed story of a project and its results.',
   ex:'The CPL recovery is a perfect case study.'},

  /* ---------- GENERAL PROFESSIONAL (B2) ---------- */
  {w:'thorough',        cat:'General', ar:'شامل ودقيق',
   def:'Complete and careful, with attention to detail.',
   ex:'Do a thorough check of the pixel before launch.'},
  {w:'concise',         cat:'General', ar:'موجز',
   def:'Short and clear, without unnecessary words.',
   ex:'Keep the report concise \u2014 one page maximum.'},
  {w:'substantial',     cat:'General', ar:'كبير ومهم',
   def:'Large in amount or importance.',
   ex:'That is a substantial improvement in cost.'},
  {w:'feasible',        cat:'General', ar:'قابل للتنفيذ',
   def:'Possible to do practically.',
   ex:'Is that deadline feasible with the current team?'},
  {w:'ambiguous',       cat:'General', ar:'غامض',
   def:'Open to more than one interpretation.',
   ex:'The brief was ambiguous, so the design missed.'},
  {w:'meticulous',      cat:'General', ar:'دقيق جداً',
   def:'Very careful and precise about detail.',
   ex:'Tracking work needs someone meticulous.'},
  {w:'streamline',      cat:'General', ar:'يبسّط ويسرّع',
   def:'To make a process simpler and more efficient.',
   ex:'Streamline the approval flow before hiring.'},
  {w:'bottleneck',      cat:'General', ar:'عنق الزجاجة',
   def:'A point that slows the whole process.',
   ex:'Approvals are the bottleneck, not the work.'},
  {w:'proactive',       cat:'General', ar:'استباقي',
   def:'Acting before a problem appears.',
   ex:'Be proactive: send the update before they ask.'},
  {w:'accountable',     cat:'General', ar:'مسؤول ومحاسَب',
   def:'Responsible and answerable for results.',
   ex:'One person must be accountable for the budget.'},
  {w:'resilient',       cat:'General', ar:'قادر على التعافي',
   def:'Able to recover quickly from difficulty.',
   ex:'The account was resilient despite the algorithm change.'},
  {w:'discrepancy',     cat:'General', ar:'تباين/اختلاف',
   def:'A difference between things that should match.',
   ex:'There is a discrepancy between Meta and GA4 numbers.'},
  {w:'ramp up',         cat:'General', ar:'يزيد تدريجياً',
   def:'To increase gradually.',
   ex:'Ramp up spend slowly or you will break learning.'},
  {w:'iterate',         cat:'General', ar:'يحسّن بالتكرار',
   def:'To repeat with improvements each time.',
   ex:'Iterate on the winning creative, do not start over.'},
  {w:'overwhelming',    cat:'General', ar:'غامر/طاغي',
   def:'Very great in amount or effect.',
   ex:'The response was overwhelming \u2014 1,544 leads.'},
  {w:'preliminary',     cat:'General', ar:'مبدئي',
   def:'Coming before the main part.',
   ex:'These are preliminary numbers; wait for the final pull.'},
  {w:'subsequent',      cat:'General', ar:'لاحق',
   def:'Coming after something else.',
   ex:'Subsequent campaigns performed better.'},
  {w:'inherent',        cat:'General', ar:'متأصل',
   def:'Existing as a natural, permanent part.',
   ex:'There is inherent risk in any new channel.'},
  {w:'deteriorate',     cat:'General', ar:'يتدهور',
   def:'To become worse.',
   ex:'Performance deteriorated after we widened the audience.'},
  {w:'mitigate',        cat:'General', ar:'يخفّف',
   def:'To make something less severe.',
   ex:'Set a spend cap to mitigate the risk.'},
  {w:'criterion',       cat:'General', ar:'معيار',
   def:'A standard used to judge something.',
   ex:'Cost per qualified lead is the only criterion.'},
  {w:'consensus',       cat:'General', ar:'إجماع',
   def:'General agreement among a group.',
   ex:'We reached consensus on the Q4 plan.'},
  {w:'implication',     cat:'General', ar:'تأثير/تبعة',
   def:'A possible effect of a decision.',
   ex:'The implication is that we need a second buyer.'},
  {w:'arbitrary',       cat:'General', ar:'اعتباطي',
   def:'Based on random choice rather than reason.',
   ex:'That budget split feels arbitrary.'},
  {w:'nuance',          cat:'General', ar:'فارق دقيق',
   def:'A small but important difference.',
   ex:'There is a nuance between reach and frequency.'},
  {w:'coherent',        cat:'General', ar:'متماسك',
   def:'Logical and consistent.',
   ex:'The deck needs a coherent story, not just slides.'},
  {w:'explicit',        cat:'General', ar:'صريح وواضح',
   def:'Stated clearly and in detail.',
   ex:'Be explicit about what you need from the client.'},
  {w:'implicit',        cat:'General', ar:'ضمني',
   def:'Suggested without being stated directly.',
   ex:'The implicit expectation was weekend availability.'},
  {w:'incentive',       cat:'General', ar:'حافز',
   def:'A reward that encourages behaviour.',
   ex:'The bonus is an incentive to hit the target.'},
  {w:'threshold',       cat:'General', ar:'الحد الأدنى',
   def:'The level at which something starts to happen.',
   ex:'There is a minimum spend threshold on this channel.'},
  {w:'versatile',       cat:'General', ar:'متعدد الاستخدامات',
   def:'Able to adapt to many different uses.',
   ex:'Video is the most versatile format right now.'},
  {w:'obsolete',        cat:'General', ar:'متجاوز/منتهي',
   def:'No longer used because something better exists.',
   ex:'Manual bid management is almost obsolete.'},
  {w:'prevalent',       cat:'General', ar:'سائد/منتشر',
   def:'Common in a particular place or time.',
   ex:'Short-form video is prevalent across the Gulf.'},
  {w:'cumulative',      cat:'General', ar:'تراكمي',
   def:'Increasing by successive additions.',
   ex:'Cumulative reach is 1.2 million this quarter.'},
  {w:'discretion',      cat:'General', ar:'تقدير شخصي',
   def:'Freedom to decide what should be done.',
   ex:'Use your discretion on small budget moves.'},
  {w:'hierarchy',       cat:'General', ar:'تسلسل هرمي',
   def:'A system ranking people by authority.',
   ex:'Understand the hierarchy before the first meeting.'},
  {w:'autonomy',        cat:'General', ar:'استقلالية',
   def:'The freedom to act independently.',
   ex:'They gave me full autonomy over the account.'},
  {w:'pragmatic',       cat:'General', ar:'عملي/واقعي',
   def:'Dealing with things practically rather than theoretically.',
   ex:'Be pragmatic: ship the fix, then improve it.'},
  {w:'redundant',       cat:'General', ar:'زائد عن الحاجة',
   def:'No longer needed because it repeats something.',
   ex:'That second approval step is redundant.'},
  {w:'pertinent',       cat:'General', ar:'ذو صلة',
   def:'Directly relevant to the matter at hand.',
   ex:'Keep the report to pertinent numbers only.'},
  {w:'nominal',         cat:'General', ar:'اسمي/رمزي',
   def:'Very small, or existing in name only.',
   ex:'There is a nominal fee for the certification.'},
  {w:'tangible',        cat:'General', ar:'ملموس',
   def:'Real and able to be clearly seen or measured.',
   ex:'Show tangible results, not impressions.'},
  {w:'intangible',      cat:'General', ar:'غير ملموس',
   def:'Not able to be measured or touched.',
   ex:'Brand trust is intangible but it sells.'},
  {w:'prerequisite',    cat:'General', ar:'شرط مسبق',
   def:'Something required before something else.',
   ex:'Two years of experience is a prerequisite here.'},
  {w:'comprehensive',   cat:'General', ar:'شامل',
   def:'Including everything necessary.',
   ex:'Give me a comprehensive breakdown by ad set.'},
  {w:'plausible',       cat:'General', ar:'معقول/محتمل',
   def:'Seeming reasonable or probable.',
   ex:'That is a plausible explanation for the drop.'},
  {w:'inevitable',      cat:'General', ar:'حتمي',
   def:'Certain to happen.',
   ex:'Creative fatigue is inevitable after three weeks.'},
  {w:'substantiate',    cat:'General', ar:'يثبت بالأدلة',
   def:'To provide evidence for a claim.',
   ex:'Substantiate every number in the proposal.'},
  {w:'adhere',          cat:'General', ar:'يلتزم بـ',
   def:'To follow a rule or plan closely.',
   ex:'Adhere to the brand guidelines on every asset.'},
  {w:'premise',         cat:'General', ar:'افتراض أساسي',
   def:'A statement assumed to be true as a basis.',
   ex:'The whole plan rests on a false premise.'},
  {w:'counterpart',     cat:'General', ar:'النظير',
   def:'A person with the same role elsewhere.',
   ex:'My counterpart in the Riyadh office handles media.'},
  {w:'discretionary',   cat:'General', ar:'تقديري',
   def:'Decided by judgement, not by rule.',
   ex:'The discretionary budget is TL 5,000.'},
  {w:'attrition',       cat:'General', ar:'تساقط/فقد تدريجي',
   def:'A gradual reduction in numbers.',
   ex:'Customer attrition is 8% a year.'},
  {w:'nuanced',         cat:'General', ar:'دقيق ومتعدد الطبقات',
   def:'Showing fine distinctions.',
   ex:'The Gulf market needs a more nuanced message.'},
  {w:'encompass',       cat:'General', ar:'يشمل',
   def:'To include a wide range of things.',
   ex:'The role encompasses strategy and execution.'},
  {w:'subsidiary',      cat:'General', ar:'شركة تابعة',
   def:'A company owned by a larger one.',
   ex:'The agency is a subsidiary of a holding group.'},
  {w:'disparity',       cat:'General', ar:'تفاوت',
   def:'A great difference or imbalance.',
   ex:'There is a pay disparity between markets.'},
  {w:'amenable',        cat:'General', ar:'متقبّل/متفهم',
   def:'Open to suggestion or agreement.',
   ex:'They are amenable to a longer contract.'},
  {w:'comply',          cat:'General', ar:'يمتثل',
   def:'To act in accordance with a rule or request.',
   ex:'All creative must comply with Meta policy.'},
  {w:'contend',         cat:'General', ar:'يؤكد/يواجه',
   def:'To argue a position, or to compete.',
   ex:'I would contend that creative is the main lever.'},
  {w:'deterrent',       cat:'General', ar:'رادع',
   def:'Something that discourages an action.',
   ex:'A penalty is a deterrent, not a punishment.'},
  {w:'surplus',         cat:'General', ar:'فائض',
   def:'An amount left over after needs are met.',
   ex:'We ended the quarter with a small surplus.'},
  {w:'deficit',         cat:'General', ar:'عجز',
   def:'A shortage, or the amount by which something falls short.',
   ex:'Two months of no income created a deficit.'},
  {w:'trajectory',      cat:'General', ar:'مسار',
   def:'The path something is following over time.',
   ex:'The trajectory is upward, which is what matters.'},
  {w:'vicinity',        cat:'General', ar:'محيط/جوار',
   def:'The area near a place.',
   ex:'I am looking for roles in the Riyadh vicinity.'},
  {w:'redundancy',      cat:'General', ar:'تكرار غير ضروري',
   def:'Unnecessary repetition, or job loss.',
   ex:'Cut the redundancy \u2014 say it once.'},
  {w:'envisage',        cat:'General', ar:'يتصور',
   def:'To imagine as a future possibility.',
   ex:'I envisage running the agency within four years.'},
  {w:'subordinate',     cat:'General', ar:'تابع',
   def:'Lower in rank or importance.',
   ex:'He treats nobody as subordinate.'},
  {w:'arbitrate',       cat:'General', ar:'يحكم بين طرفين',
   def:'To settle a dispute between two sides.',
   ex:'We had to arbitrate between sales and creative.'},
  {w:'caveat',          cat:'General', ar:'تحذير/شرط',
   def:'A warning or condition attached to a statement.',
   ex:'One caveat: the data excludes the last three days.'},
  {w:'consolidate',     cat:'General', ar:'يدمج',
   def:'To combine several things into one.',
   ex:'Consolidate the reports into a single dashboard.'},
  {w:'diligent',        cat:'General', ar:'مجتهد',
   def:'Showing careful and persistent effort.',
   ex:'Diligent tracking work prevents expensive mistakes.'},
  {w:'incremental',     cat:'General', ar:'تدريجي',
   def:'Increasing in small steps.',
   ex:'Incremental gains beat one big bet.'},
  {w:'precedent',       cat:'General', ar:'سابقة',
   def:'An earlier case used as an example or rule.',
   ex:'Do not set a precedent you cannot maintain.'},
  {w:'integral',        cat:'General', ar:'جوهري',
   def:'Necessary as part of a whole.',
   ex:'Tracking is integral to media buying.'},
  {w:'proficient',      cat:'General', ar:'متمكّن',
   def:'Competent and skilled at something.',
   ex:'You need to be proficient in Excel.'},
  {w:'proximity',       cat:'General', ar:'قرب',
   def:'Nearness in space or time.',
   ex:'Proximity to clients matters less than results.'},
  {w:'underpin',        cat:'General', ar:'يدعم أساساً',
   def:'To support or form the basis of.',
   ex:'Good data underpins every decision we make.'},
  {w:'verdict',         cat:'General', ar:'حكم/قرار نهائي',
   def:'A final decision or judgement.',
   ex:'The verdict was: keep the campaign running.'}
];

/* ---------------------------------------------------------------
   DAILY VOCABULARY — 5 words a day, same words all day
   Deterministic by date so the list does not reshuffle on refresh.
   --------------------------------------------------------------- */
const VOCAB_PER_DAY = 5;

function vocabDay(){
  /* days since epoch — stable across refreshes, changes at midnight */
  const d = new Date();
  const start = new Date(2026, 0, 1);
  return Math.floor((d - start) / 86400000);
}

function todaysVocab(){
  const day = vocabDay();
  const total = VOCAB.length;
  const per = VOCAB_PER_DAY;
  const out = [];
  /* walk the list so a full cycle covers everything exactly once */
  for(let i = 0; i < per; i++){
    out.push(VOCAB[((day * per) + i) % total]);
  }
  return out;
}

function vocabKey(word){
  return 'v_' + word.replace(/[^A-Za-z]/g, '_');
}
